apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.exclusions: |
    - apiGroups:
      - repositories.stash.appscode.com
      kinds:
      - Snapshot
      clusters:
      - "*.local"
    - apiGroups:
      - "*"
      kinds:
      - PodTemplate
      clusters:
      - https://vc01cl01-wcp.h2o-4-9763.h2o.vmware.com:6443

  # By default all resource group/kinds are included. The resource.inclusions setting allows customizing
  # list of included group/kinds.
  resource.inclusions: |
    - apiGroups:
      - repositories.stash.appscode.com
      kinds:
      - Snapshot
      clusters:
      - "*.local"
    - apiGroups:
      - "run.tanzu.vmware.com"
      kinds:
      - TanzuKubernetesAddon
      - TanzuKubernetesCluster
      - TanzuKubernetesRelease
      - TkgServiceConfiguration
      clusters:
      - https://vc01cl01-wcp.h2o-4-9763.h2o.vmware.com:6443
    - apiGroups:
      - "cluster.x-k8s.io"
      kinds:
      - Cluster
      - Machine
      - MachineDeployment
      - MachineHealthCheck
      - MachineSet
      clusters:
      - https://vc01cl01-wcp.h2o-4-9763.h2o.vmware.com:6443
    - apiGroups:
      - "vmoperator.vmware.com"
      kinds: 
      - "*"
      clusters:
      - https://vc01cl01-wcp.h2o-4-9763.h2o.vmware.com:6443
    - apiGroups:
      - "controlplane.cluster.x-k8s.io"
      - "bootstrap.cluster.x-k8s.io"
      kinds: 
      - KubeadmControlPlane
      - KubeadmConfig
      - KubeadmConfigTemplate
      clusters:
      - https://vc01cl01-wcp.h2o-4-9763.h2o.vmware.com:6443
    - apiGroups:
      - "infrastructure.cluster.vmware.com"
      kinds: 
      - "*"
      clusters:
      - https://vc01cl01-wcp.h2o-4-9763.h2o.vmware.com:6443
      - apiGroups:
      - "rbac.authorization.k8s.io"
      kinds: 
      - Role
      - RoleBinding
      clusters:
      - https://vc01cl01-wcp.h2o-4-9763.h2o.vmware.com:6443

