apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: sv-cluster-argocd-ns
  namespace: argocd
type: Opaque
stringData:
  config: |
    {
    "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImJONURLT0QwWHNLc0J3TXltdkZZa1N5UFBHRGtNZG9fNUhRN3ZOSWVUMkEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJuczMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiYXJnb2NkLXJvYm90LXRva2VuLWNtbHo5Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFyZ29jZC1yb2JvdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImU4ZWZjYjg3LTYzOTMtNDRlYy1hNWI4LTVlOGRhNGM3M2M4MSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpuczM6YXJnb2NkLXJvYm90In0.ELhFrCwCZUV_xA9xeJw63Sb6f8Gmz7tC8kb24vDnknhhXvDUbjdPkFEdrCq-7oixqwuh8ddmLtRV-IJa1fwUrbmA5R4MCQLGYNOBlb-CsGw4OuoyuXU-GhVdhXM9uQIu7d0Ha0-I8D_SiSFg9vvKZambgwHURa7IhJ7FkDxyvVptPRGfK1BzuwR0Pm-3iF8QGLz59OX62T0IeHMhLcmj5lpHp5BRLM8MNY7f7kKhbyQS9M5jTvyANlPVwSABQIeAEvjwY5YvxOCLjdKh6jN8CZ5NeRtn0EUvxzf0C3fppscriq0uVVyUxbw5kbMI-FTLH4p-0tY7z_JqsXHrhxEIvw",
        "tlsClientConfig": {
        "insecure": true
        }
    }
  name: sv-clu01-argocd-ns
  namespaces: ns3
  server: https://vc01cl01-wcp.h2o-4-9763.h2o.vmware.com:6443