apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkg-cluster-1
  namespace: ns1
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-small
      storageClass: vc01cl01-t0compute
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
    nodePools:
    - name: worker-nodepool1
      replicas: 1
      vmClass: best-effort-small
      storageClass: vc01cl01-t0compute
      labels:
        app: broker1
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
    - name: worker-nodepool2
      replicas: 3
      vmClass: best-effort-large
      storageClass: vc01cl01-t0compute
      labels:
        app: broker2
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55           #storageclass for worker nodes
