apiVersion: run.tanzu.vmware.com/v1alpha1               #TKG API endpoint
kind: TanzuKubernetesCluster                            #required parameter
metadata:
  name: tkg-cluster-2                                   #cluster name, user defined
  namespace: ns1                                        #supervisor namespace
spec:
  distribution:
    fullVersion: null
    version: v1.23                                      #resolved kubernetes version
  topology:
    controlPlane:
      count: 1                                          #number of control plane nodes
      class: best-effort-small                          #vmclass for control plane nodes
      storageClass: vc01cl01-t0compute                  #storageclass for control plane
    workers:
      count: 1                                          #number of worker nodes
      class: best-effort-small                          #vmclass for worker nodes
      storageClass: vc01cl01-t0compute                  #storageclass for worker nodes
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 25Gi
  settings:
    storage:
      defaultClass: vc01cl01-t0compute
